src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'discriminator', type: 'string')]
#[ORM\DiscriminatorMap(['user' => User::class, 'professor' => Professor::class, 'student' => Student::class])]
#[UniqueEntity('email')]
#[UniqueEntity('username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank]
    #[Assert\Email]
    #[Assert\Length(max: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string|null The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 100)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $lastName = null;

    #[ORM\Column(length: 80)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 80)]
    private ?string $username = null;

    private ?string $plainPassword = null;

    #[ORM\OneToOne(targetEntity: AvatarFile::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private ?AvatarFile $avatar = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName.' '.$this->lastName;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function getAvatar(): ?AvatarFile
    {
        return $this->avatar;
    }

    public function setAvatar(?AvatarFile $avatar): void
    {
        $this->avatar = $avatar;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\AvatarFile;
use App\Entity\User;
use App\Form\UserSettingsType;
use App\Repository\UserRepository;
use App\Services\AvatarService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Vich\UploaderBundle\FileAbstraction\ReplacingFile;

#[Route('/user')]
final class UserController extends AbstractController
{
    #[Route('/profile/{username}', name: 'app_user_profile', methods: ['GET'])]
    public function profile(string $username, UserRepository $userRepository): Response
    {
        $user = $userRepository->findOneBy(['username' => $username]);

        return $this->render('/user/profile.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/settings', name: 'app_user_settings')]
    public function settings(Request $request, EntityManagerInterface $entityManager, AvatarService $avatarService): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $settingsForm = $this->createForm(UserSettingsType::class, $user);
        $avatars = $avatarService->getAllAvatarsImages();

        try {
            $settingsForm->handleRequest($request);
            if ($settingsForm->isSubmitted() && $settingsForm->isValid()) {
                $avatarPath = $settingsForm->get('defaultAvatar')->getData();
                $deleteAvatar = boolval($settingsForm->get('deleteAvatar')->getData());

                if ($avatarPath && $avatarService->exists($avatarPath)) {
                    $avatarPath = $avatarService->makeAbsolute($avatarPath);

                    $deleteAvatarOption = new AvatarFile();
                    $deleteAvatarOption->setFile(new ReplacingFile($avatarPath));
                    $user->setAvatar($deleteAvatarOption);
                } elseif ($deleteAvatar) {
                    $user->setAvatar(null);
                }

                $entityManager->persist($user);
                $entityManager->flush();

                $this->addFlash('success', 'Suas configurações foram atualizadas.');

                return $this->redirectToRoute('app_user_settings');
            }
        } catch (\Exception $exception) {
            $this->addFlash('error', 'Erro ao atualizar o seu perfil.');

            return $this->redirectToRoute('app_user_settings');
        }

        return $this->render('/user/settings.html.twig', [
            'settingsForm' => $settingsForm,
            'avatars' => $avatars,
        ]);
    }
}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Profile{% endblock %}

{% block body %}
    <div class="page-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-auto">
                    <span
                        class="avatar avatar-xl"
                        {% if user.avatar %}
                            style="background-image: url('{{ vich_uploader_asset(user.avatar) }}')"
                        {% endif %}
                    >
                        {{ not user.avatar ? user.fullName|initials[:2] : '' }}
                    </span>
                </div>
                <div class="col">
                    <h2 class="page-title">{{ user.fullName }}</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="page-body">

    </div>
{% endblock %}

templates/user/settings.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Configurações{% endblock %}

{% block body %}
    <div class="page-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col">
                    <h2 class="page-title">Configurações</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="page-body">
        <div class="container">
            <div class="card">
                {{ form_start(settingsForm, { attr: {id: 'form-user-settings'}|merge(stimulus_controller('user-settings', { userInitials: app.user.fullName|initials[:2] }).toArray()) }) }}
                <div class="card-body">
                    <h2>Minha Conta</h2>

                    {{ form_errors(settingsForm) }}

                    <h3 class="card-title">Imagem de Perfil</h3>
                    <div class="row align-items-center">
                        <div class="col-auto">
                            {{ form_row(settingsForm.deleteAvatar, { attr: stimulus_target('user-settings', 'deleteAvatarOption').toArray() }) }}

                            <button
                                type="button"
                                class="avatar avatar-xl border-0"
                                data-bs-toggle="modal"
                                data-bs-target="#imagePerfilModal"
                                {% if app.user.avatar %}
                                    style="background-image: url('{{ vich_uploader_asset(app.user.avatar) }}')"
                                {% endif %}
                                {{ stimulus_target('user-settings', 'userAvatar') }}
                            >
                                <span {{ stimulus_target('user-settings', 'avatarInitials') }}>{{ not app.user.avatar ? app.user.fullName|initials[:2] : '' }}</span>
                                <span
                                    class="badge badge-sm badge-icononly badge-pill bg-blue text-blue-fg">{{ ux_icon('tabler:pencil', { class: 'icon'}) }}</span>
                            </button>

                            <div
                                class="modal fade"
                                id="imagePerfilModal"
                                data-bs-backdrop="static"
                                data-bs-keyboard="false"
                                tabindex="-1"
                                aria-labelledby="staticBackdropLabel"
                                aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Imagem de Perfil</h5>
                                            <button
                                                type="button"
                                                class="btn-close"
                                                data-bs-dismiss="modal"
                                                aria-label="Close"
                                                {{ stimulus_action('user-settings', 'updateAvatarImage', 'click') }}
                                            ></button>
                                        </div>
                                        <div class="modal-body">
                                            <fieldset
                                                class="collapse show"
                                                {{ stimulus_target('user-settings', 'avatarFieldset') }}
                                            >
                                                <div class="row g-2">
                                                    {% for option in settingsForm.defaultAvatar %}
                                                        <div class="col-3">
                                                            <label class="form-imagecheck mb-2">
                                                                <input
                                                                    name="{{ field_name(option) }}"
                                                                    type="radio"
                                                                    value="{{ field_value(option) }}"
                                                                    class="form-imagecheck-input"
                                                                    {% if app.user.avatar %}
                                                                        {{ app.user.avatar.originalName in field_value(option) ? 'checked' }}
                                                                    {% endif %}
                                                                    {{ stimulus_target('user-settings', 'inputAvatar') }}
                                                                    {{ stimulus_action('user-settings', 'setAvatarImageUrl', 'change', { imageUrl: field_value(option) ? asset(field_value(option)) : ''}) }}
                                                                />
                                                                <span class="form-imagecheck-figure">
                                                                <img
                                                                    src="{{ asset(field_value(option)) }}"
                                                                    alt=""
                                                                    class="form-imagecheck-image"
                                                                />
                                                            </span>
                                                            </label>
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                            </fieldset>
                                            <div class="hr-text">Ou</div>
                                            <div class="row">
                                                {{ form_row(settingsForm.avatar) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-auto">
                            <button
                                type="button"
                                class="btn btn-ghost-danger" {{ stimulus_action('user-settings', 'deleteAvatar') }}
                            >
                                Delete avatar
                            </button>
                        </div>
                    </div>

                    <h3 class="cart-title mt-3">Informações do Perfil</h3>

                    <div class="row row-gap-3">
                        <div class="row row-gap-3">
                            {{ form_row(settingsForm.firstName, {
                                row_attr: { class: 'col-12 col-lg-6' },
                            }) }}
                            {{ form_row(settingsForm.lastName, {
                                row_attr: { class: 'col-12 col-lg-6' },
                            }) }}
                        </div>

                        <div class="row row-gap-3">
                            <div class="col-12 col-lg-6">
                                {{ form_label(settingsForm.username) }}
                                <div class="input-icon">
                                    <span class="input-icon-addon">{{ ux_icon('tabler:at', {'class': 'icon'}) }}</span>
                                    {{ form_widget(settingsForm.username, { attr: { class: 'form-control' }}) }}
                                </div>
                                {{ form_help(settingsForm.username) }}
                                {{ form_errors(settingsForm.username) }}
                            </div>

                            <div class="col-12 col-lg-6">
                                {{ form_label(settingsForm.email) }}
                                <div class="input-icon">
                                    <span
                                        class="input-icon-addon">{{ ux_icon('tabler:mail', {'class': 'icon'}) }}</span>
                                    {{ form_widget(settingsForm.email, {attr: {class: 'form-control'}}) }}
                                </div>
                                {{ form_help(settingsForm.email) }}
                                {{ form_errors(settingsForm.email) }}
                            </div>
                        </div>

                        <h3 class="cart-title m-0">Segurança</h3>

                        {% set passwordFields = {currentPassword: settingsForm.currentPassword}|merge(settingsForm.plainPassword.children) %}
                        {% for field in passwordFields %}
                            <div class="row">
                                <div class="col-12 col-lg-6">
                                    {{ form_label(field) }}
                                    <div
                                        class="input-group input-group-flat" {{ stimulus_controller('toggle_password') }}>
                                        {{ form_widget(field, {attr: stimulus_target('toggle_password', 'password').toArray()}) }}
                                        <span
                                            class="input-group-text p-0{{ field.vars.valid ? '' : ' border-danger' }}">
                                            <button
                                                type="button"
                                                class="link-secondary bg-transparent border-0"
                                                title="Mostrar senha"
                                                data-bs-toggle="tooltip"
                                            {{ stimulus_action('toggle_password', 'toggle', 'click') }}
                                            >
                                                {{ ux_icon('tabler:eye', {class: 'icon'}) }}
                                            </button>
                                        </span>
                                    </div>
                                    {{ form_help(field) }}
                                    {{ form_errors(field) }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card-footer">
                    <div class="btn-list">
                        <a href="{{ path('app_user_settings') }}" class="btn">Cancelar</a>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </div>
                {{ form_end(settingsForm) }}
            </div>
        </div>
    </div>
{% endblock %}